import type { Zone, CleanupReport, Reward, Notification, Sponsor } from "@/types"

export const mockSponsors: Sponsor[] = [
  { id: "s1", name: "EcoGreen Corp", logo: "/eco-green-logo.jpg", rewardDescription: "20% off eco products" },
  { id: "s2", name: "CleanCity Foundation", logo: "/clean-city-foundation-logo.jpg", rewardDescription: "Cleanup tool kit" },
  {
    id: "s3",
    name: "SolarPower Inc",
    logo: "/solar-power-company-logo.jpg",
    rewardDescription: "Solar streetlight installation",
  },
]

export const mockZones: Zone[] = [
  {
    id: "z1",
    name: "Greenwood Heights",
    location: "123 Oak Street, District A",
    coordinates: { lat: 40.7128, lng: -74.006 },
    population: 12500,
    baselineScore: 45,
    currentScore: 78,
    totalPoints: 2450,
    representative: { name: "Sarah Chen", email: "sarah@greenwood.org", phone: "555-0101" },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-12-10T15:30:00Z",
    lastActivityDate: "2024-12-10T14:00:00Z",
    status: "active",
  },
  {
    id: "z2",
    name: "Riverside Commons",
    location: "456 River Road, District B",
    coordinates: { lat: 40.7589, lng: -73.9851 },
    population: 8200,
    baselineScore: 52,
    currentScore: 85,
    totalPoints: 3120,
    representative: { name: "Marcus Johnson", email: "marcus@riverside.org" },
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-12-09T11:20:00Z",
    lastActivityDate: "2024-12-09T10:00:00Z",
    status: "active",
  },
  {
    id: "z3",
    name: "Sunset Valley",
    location: "789 Valley View, District C",
    population: 15000,
    baselineScore: 38,
    currentScore: 62,
    totalPoints: 1890,
    createdAt: "2024-03-10T14:00:00Z",
    updatedAt: "2024-12-08T09:45:00Z",
    lastActivityDate: "2024-12-07T16:30:00Z",
    status: "active",
  },
  {
    id: "z4",
    name: "Harbor District",
    location: "321 Dock Street, District D",
    coordinates: { lat: 40.6892, lng: -74.0445 },
    population: 6800,
    baselineScore: 41,
    currentScore: 71,
    totalPoints: 2180,
    representative: { name: "Elena Rodriguez", email: "elena@harbor.org", phone: "555-0404" },
    createdAt: "2024-01-20T11:30:00Z",
    updatedAt: "2024-12-10T08:15:00Z",
    lastActivityDate: "2024-12-10T07:00:00Z",
    status: "active",
  },
  {
    id: "z5",
    name: "Central Park West",
    location: "555 Central Ave, District E",
    population: 22000,
    baselineScore: 55,
    currentScore: 91,
    totalPoints: 4250,
    representative: { name: "David Kim", email: "david@cpw.org" },
    createdAt: "2024-01-05T08:00:00Z",
    updatedAt: "2024-12-11T10:00:00Z",
    lastActivityDate: "2024-12-11T09:30:00Z",
    status: "active",
  },
]

export const mockReports: CleanupReport[] = [
  {
    id: "r1",
    zoneId: "z1",
    zoneName: "Greenwood Heights",
    beforePhoto: "/dirty-street-with-litter.jpg",
    afterPhoto: "/clean-street-after-cleanup.jpg",
    trashBags: 12,
    weightKg: 45,
    cleanupDate: "2024-12-10",
    coordinates: { lat: 40.7128, lng: -74.006 },
    wasteTags: ["plastics", "general", "recyclables"],
    status: "verified",
    score: 85,
    scoreBreakdown: { volumeScore: 30, cleanlinessImprovement: 25, frequencyBonus: 15, wasteTypeImpact: 15, total: 85 },
    submittedAt: "2024-12-10T14:30:00Z",
    verifiedAt: "2024-12-10T15:00:00Z",
    verifiedBy: "admin",
    aiClassification: {
      confidence: 0.92,
      detectedWaste: ["plastics", "general"],
      cleanlinessBeforeScore: 35,
      cleanlinessAfterScore: 82,
      verificationStatus: "pass",
    },
  },
  {
    id: "r2",
    zoneId: "z2",
    zoneName: "Riverside Commons",
    beforePhoto: "/park-with-garbage.jpg",
    afterPhoto: "/clean-park-after-volunteers.jpg",
    trashBags: 18,
    weightKg: 62,
    cleanupDate: "2024-12-09",
    wasteTags: ["organic", "plastics", "recyclables"],
    status: "verified",
    score: 92,
    scoreBreakdown: { volumeScore: 35, cleanlinessImprovement: 28, frequencyBonus: 12, wasteTypeImpact: 17, total: 92 },
    submittedAt: "2024-12-09T10:15:00Z",
    verifiedAt: "2024-12-09T11:00:00Z",
    aiClassification: {
      confidence: 0.88,
      detectedWaste: ["organic", "plastics"],
      cleanlinessBeforeScore: 28,
      cleanlinessAfterScore: 88,
      verificationStatus: "pass",
    },
  },
  {
    id: "r3",
    zoneId: "z5",
    zoneName: "Central Park West",
    beforePhoto: "/sidewalk-with-trash.jpg",
    afterPhoto: "/pristine-sidewalk.jpg",
    trashBags: 25,
    weightKg: 95,
    cleanupDate: "2024-12-11",
    coordinates: { lat: 40.7831, lng: -73.9712 },
    wasteTags: ["plastics", "e-waste", "recyclables", "general"],
    status: "pending",
    submittedAt: "2024-12-11T09:45:00Z",
  },
  {
    id: "r4",
    zoneId: "z4",
    zoneName: "Harbor District",
    beforePhoto: "/beach-with-debris.jpg",
    afterPhoto: "/clean-beach-shore.jpg",
    trashBags: 30,
    weightKg: 120,
    cleanupDate: "2024-12-10",
    wasteTags: ["plastics", "general", "hazardous"],
    status: "pending",
    submittedAt: "2024-12-10T07:30:00Z",
  },
]

export const mockRewards: Reward[] = [
  {
    id: "rw1",
    zoneId: "z5",
    zoneName: "Central Park West",
    type: "solar-streetlight",
    tier: "gold",
    period: "November 2024",
    awardedAt: "2024-12-01T00:00:00Z",
    sponsor: mockSponsors[2],
    claimed: true,
  },
  {
    id: "rw2",
    zoneId: "z2",
    zoneName: "Riverside Commons",
    type: "trash-bins",
    tier: "silver",
    period: "November 2024",
    awardedAt: "2024-12-01T00:00:00Z",
    sponsor: mockSponsors[1],
    claimed: true,
  },
  {
    id: "rw3",
    zoneId: "z1",
    zoneName: "Greenwood Heights",
    type: "certificate",
    tier: "bronze",
    period: "November 2024",
    awardedAt: "2024-12-01T00:00:00Z",
    claimed: false,
  },
  {
    id: "rw4",
    zoneId: "z4",
    zoneName: "Harbor District",
    type: "cleanup-tools",
    tier: "gold",
    period: "October 2024",
    awardedAt: "2024-11-01T00:00:00Z",
    sponsor: mockSponsors[1],
    claimed: true,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "reminder",
    title: "Weekly Cleanup Reminder",
    message: "Time for this week's community cleanup! Rally your neighbors.",
    read: false,
    createdAt: "2024-12-11T08:00:00Z",
  },
  {
    id: "n2",
    type: "alert",
    title: "Your Zone is Falling Behind!",
    message: "Greenwood Heights dropped to 4th place. Time to step up!",
    zoneId: "z1",
    read: false,
    createdAt: "2024-12-10T18:00:00Z",
  },
  {
    id: "n3",
    type: "score-change",
    title: "Score Updated",
    message: "Your latest cleanup earned 85 points!",
    zoneId: "z1",
    read: true,
    createdAt: "2024-12-10T15:00:00Z",
  },
  {
    id: "n4",
    type: "reward",
    title: "Reward Unlocked!",
    message: "Congratulations! Your zone earned a Bronze certificate.",
    zoneId: "z1",
    read: true,
    createdAt: "2024-12-01T00:00:00Z",
    actionUrl: "/rewards",
  },
  {
    id: "n5",
    type: "announcement",
    title: "Holiday Cleanup Challenge",
    message: "Double points for all cleanups during the holiday season!",
    read: false,
    createdAt: "2024-12-09T10:00:00Z",
  },
]
